theme: jekyll-theme-minimal
title: Grayson's homepage
description: Hi! If you want, you can bookmark this page to get more updates on my latest projects!
github:
  is_project_page: true
  repository_url: https://github.com/YOUR-USERNAME/YOUR-REPO
